route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: GMAIL_ADDRESS
    from: GMAIL_APP_ID
    smarthost: smtp.gmail.com:587
    auth_username: GMAIL_APP_ID
    auth_identity: GMAIL_APP_ID
    auth_password: GMAIL_APP_PASS
