# global:
#   scrape_interval: 15s
#   external_labels:
#     monitor: 'prometheus'

# scrape_configs:
#   - job_name: 'prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:9090']
#   - job_name: 'node_exporter'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['ec2-34-226-211-183.compute-1.amazonaws.com:9100']

# global:
#   scrape_interval: 1s
#   evaluation_interval: 1s

# scrape_configs:
#   - job_name: 'prometheus'
#     scrape_interval: 5s
#     static_configs:
#       - targets: ['localhost:9090']
#   - job_name: 'node'
#     ec2_sd_configs:
#       - region: us-east-1
#         access_key: EC2_RO_ACCESS_KEY
#         secret_key: EC2_RO_SECRET_KEY
#         port: 9100

global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: EC2_RO_ACCESS_KEY
        secret_key: EC2_RO_SECRET_KEY
        port: 9100

